name: jaspr_bloc
description: A state management package for Jaspr that implements the BLoC pattern, enabling Jaspr apps to handle state the same way as Flutter apps.
version: 1.0.1
repository: https://github.com/arc41t3ct/jaspr_bloc

environment:
  sdk: ^3.10.8

dependencies:
  bloc: ^9.2.1
  jaspr: ^0.23.1

dev_dependencies:
  bloc_test: ^10.0.0
  jaspr_builder: ^0.23.1
  jaspr_lints: ^0.7.1
  jaspr_test: ^0.23.1
  lints: ^6.1.0
  mocktail: ^1.0.5
  test: ^1.30.0
